# Generated by Django 2.2.5 on 2019-09-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='time_left_in_quarter',
            field=models.CharField(max_length=6),
        ),
    ]
